USE Workgroup

GO

IF OBJECT_ID('TTG_BEFORE_INSERT_EMPLOYEE', 'TR') IS NOT NULL
DROP TRIGGER TTG_BEFORE_INSERT_EMPLOYEE

GO

IF OBJECT_ID('TTG_AFTER_INSERT_DELETE_EMPLOYEE', 'TR') IS NOT NULL
DROP TRIGGER TTG_AFTER_INSERT_DELETE_EMPLOYEE

GO

-- CREATE TRIGGER TTG_BEFORE_INSERT_EMPLOYEE
-- ON dbo.Employees
-- INSTEAD OF INSERT -- ANTES DA INSERCAO
-- AS
-- BEGIN
--     DECLARE @TEXT VARCHAR(50)
--     SELECT @TEXT = Name FROM INSERTED
--     PRINT @TEXT
-- END

-- GO

-- CREATE TRIGGER TTG_AFTER_INSERT_DELETE_EMPLOYEE
-- ON dbo.Employees
-- AFTER INSERT, DELETE
-- AS
-- BEGIN
    
--     DECLARE @TEXT VARCHAR(255)
--     SELECT @TEXT = CONCAT('INSERTED: ', TRIM(Name)) FROM INSERTED
--     INSERT INTO dbo.Log ([Message]) VALUES (@TEXT)

--     SELECT @TEXT = CONCAT('DELETED: ', TRIM(Name)) FROM DELETED
--     INSERT INTO dbo.Log ([Message]) VALUES (@TEXT)

-- END

GO